### ISSUE TITLE
[nice to have] Autopadding

### ISSUE THREAD

**Issue by derVedro** [attltb/UFBL#2]
If I understand it right, there is no autopadding for binary blobs theirs row sizes are not a multiple of aliment. Is it possible to handle that somehow cleverly?

**Comment by attltb** [comment]
Would you mind tell me what did you mean by the autopadding with example? I don't understand what did you mean correctly.

**Comment by derVedro** [comment]
Hey, I need a couple of days to test and write an sane answer. Unfortunately I only have a few hours per week for it. In general my question is about images with arbitrary widths. How good is your algorithm with it? As I understand it, each line should be padded to fill the alignment of 8. But what if it isn't?

I wanted to made a simple small example with 3 bytes data: xFF, x00, xFF to illustrate the problem. that can be a 8x3 or 6x4 image (just as simple as possible) but got some strange results. I think the dimension here are too small to make a sane example. But may be you got a feeling of what my problem is.

**Comment by derVedro** [comment]
My last stand is, that if a line breaks somethere inside of the byte, the byte is truncated and the new line begins with the next byte. Is it possible to avoid it? Will UFBL handle it some day?

**Comment by attltb** [comment]
My algorithm assumes that the input image has some padding bits at the end of each rows to make next row starts at new byte/word/dword/qword. There is 4 alignment option for now. 1, 2, 4, 8.  For 8x3, you would be able to get correct result just by using 1 as the last argument when you call the labeling function, like `Labeling_BMRS_X64(dest, source, 3, 8, 1)`. The default value of this last parameter is 8 for X64 algorithms. That's the reason why you got the incorrect result.

For 6x4 image without padding bits, however, my algorithm cannot handle it correctly for now. Please wait a little. I'm currently generalizing my algorithms to the case with alignment 0, and most-significant-bit-first formats.

**Comment by attltb** [comment]
By the way, it looks like PBM images also have some padding bits at the end of each rows. (I checked some of them.) Last bits of each rows are saved at the most-significant-bits, so the padding bits are at the least-significant-area. It also saves black as bit 1, and white as bit 0. I'm also generalizing my library to be able to deal this case.

**Comment by attltb** [comment]
UFBL now supports various bitonal format, including most-significant-bit first one. Please check the latest version.
